package cn.joytur.modules.wechat.entities.base;

import com.jfinal.plugin.activerecord.IBean;

import cn.joytur.common.mvc.entities.DataModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWechatSubscribe<M extends BaseWechatSubscribe<M>> extends DataModel<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setAppName(java.lang.String appName) {
		set("app_name", appName);
		return (M)this;
	}
	
	public java.lang.String getAppName() {
		return getStr("app_name");
	}

	public M setAppCode(java.lang.String appCode) {
		set("app_code", appCode);
		return (M)this;
	}
	
	public java.lang.String getAppCode() {
		return getStr("app_code");
	}

	public M setAppId(java.lang.String appId) {
		set("app_id", appId);
		return (M)this;
	}
	
	public java.lang.String getAppId() {
		return getStr("app_id");
	}

	public M setAppSecret(java.lang.String appSecret) {
		set("app_secret", appSecret);
		return (M)this;
	}
	
	public java.lang.String getAppSecret() {
		return getStr("app_secret");
	}

	public M setAppType(java.lang.Long appType) {
		set("app_type", appType);
		return (M)this;
	}
	
	public java.lang.Long getAppType() {
		return getLong("app_type");
	}

	public M setIsEncryptMessage(java.lang.Long isEncryptMessage) {
		set("is_encrypt_message", isEncryptMessage);
		return (M)this;
	}
	
	public java.lang.Long getIsEncryptMessage() {
		return getLong("is_encrypt_message");
	}

	public M setEncodingAesKey(java.lang.String encodingAesKey) {
		set("encoding_aes_key", encodingAesKey);
		return (M)this;
	}
	
	public java.lang.String getEncodingAesKey() {
		return getStr("encoding_aes_key");
	}

	public M setStatus(java.lang.Long status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Long getStatus() {
		return getLong("status");
	}

	public M setToken(java.lang.String token) {
		set("token", token);
		return (M)this;
	}
	
	public java.lang.String getToken() {
		return getStr("token");
	}

	public M setWebAppId(java.lang.String webAppId) {
		set("web_app_id", webAppId);
		return (M)this;
	}
	
	public java.lang.String getWebAppId() {
		return getStr("web_app_id");
	}

	public M setWebAppSecret(java.lang.String webAppSecret) {
		set("web_app_secret", webAppSecret);
		return (M)this;
	}
	
	public java.lang.String getWebAppSecret() {
		return getStr("web_app_secret");
	}
	
	public M setMenuData(java.lang.String menuData) {
		set("menu_data", menuData);
		return (M)this;
	}
	
	public java.lang.String getMenuData() {
		return getStr("menu_data");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
