package cn.joytur.modules.wechat.entities.base;

import com.jfinal.plugin.activerecord.IBean;

import cn.joytur.common.mvc.entities.DataModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWechatMemberRecommend<M extends BaseWechatMemberRecommend<M>> extends DataModel<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setWechatMemberId(java.lang.String wechatMemberId) {
		set("wechat_member_id", wechatMemberId);
		return (M)this;
	}
	
	public java.lang.String getWechatMemberId() {
		return getStr("wechat_member_id");
	}

	public M setAcceptCode(java.lang.String acceptCode) {
		set("accept_code", acceptCode);
		return (M)this;
	}
	
	public java.lang.String getAcceptCode() {
		return getStr("accept_code");
	}
	
	public M setReceiveWechatMemberId(java.lang.String receiveWechatMemberId) {
		set("receive_wechat_member_id", receiveWechatMemberId);
		return (M)this;
	}
	
	public java.lang.String getReceiveWechatMemberId() {
		return get("receive_wechat_member_id");
	}
	
	public M setCashImage(java.lang.String cashImage) {
		set("cash_image", cashImage);
		return (M)this;
	}
	
	public java.lang.String getCashImage() {
		return get("cash_image");
	}

	public M setStatus(java.lang.Long status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Long getStatus() {
		return getLong("status");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
