package cn.joytur.modules.wechat.entities.base;

import com.jfinal.plugin.activerecord.IBean;

import cn.joytur.common.mvc.entities.DataModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWechatTemplate<M extends BaseWechatTemplate<M>> extends DataModel<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setEventType(java.lang.Long eventType) {
		set("event_type", eventType);
		return (M)this;
	}
	
	public java.lang.Long getEventType() {
		return getLong("event_type");
	}

	public M setEventCode(java.lang.String eventCode) {
		set("event_code", eventCode);
		return (M)this;
	}
	
	public java.lang.String getEventCode() {
		return getStr("event_code");
	}

	public M setEventKeywords(java.lang.String eventKeywords) {
		set("event_keywords", eventKeywords);
		return (M)this;
	}
	
	public java.lang.String getEventKeywords() {
		return getStr("event_keywords");
	}

	public M setResponseType(java.lang.Long responseType) {
		set("response_type", responseType);
		return (M)this;
	}
	
	public java.lang.Long getResponseType() {
		return getLong("response_type");
	}

	public M setResponseText(java.lang.String responseText) {
		set("response_text", responseText);
		return (M)this;
	}
	
	public java.lang.String getResponseText() {
		return getStr("response_text");
	}

	public M setResponseTitle(java.lang.String responseTitle) {
		set("response_title", responseTitle);
		return (M)this;
	}
	
	public java.lang.String getResponseTitle() {
		return getStr("response_title");
	}

	public M setResponseArticleUrl(java.lang.String responseArticleUrl) {
		set("response_article_url", responseArticleUrl);
		return (M)this;
	}
	
	public java.lang.String getResponseArticleUrl() {
		return getStr("response_article_url");
	}

	public M setResponsePicUrl(java.lang.String responsePicUrl) {
		set("response_pic_url", responsePicUrl);
		return (M)this;
	}
	
	public java.lang.String getResponsePicUrl() {
		return getStr("response_pic_url");
	}

	public M setResponseDescription(java.lang.String responseDescription) {
		set("response_description", responseDescription);
		return (M)this;
	}
	
	public java.lang.String getResponseDescription() {
		return getStr("response_description");
	}

	public M setSubscribeId(java.lang.String subscribeId) {
		set("subscribe_id", subscribeId);
		return (M)this;
	}
	
	public java.lang.String getSubscribeId() {
		return getStr("subscribe_id");
	}

	public M setStatus(java.lang.Long status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Long getStatus() {
		return getLong("status");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
