package cn.joytur.modules.wechat.entities.base;

import com.jfinal.plugin.activerecord.IBean;

import cn.joytur.common.mvc.entities.DataModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWechatMemberAddr<M extends BaseWechatMemberAddr<M>> extends DataModel<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setWechatMemberId(java.lang.String wechatMemberId) {
		set("wechat_member_id", wechatMemberId);
		return (M)this;
	}
	
	public java.lang.String getWechatMemberId() {
		return getStr("wechat_member_id");
	}

	public M setRealName(java.lang.String realName) {
		set("real_name", realName);
		return (M)this;
	}
	
	public java.lang.String getRealName() {
		return getStr("real_name");
	}

	public M setAddrArea(java.lang.String addrArea) {
		set("addr_area", addrArea);
		return (M)this;
	}
	
	public java.lang.String getAddrArea() {
		return getStr("addr_area");
	}
	
	public M setAddrDetail(java.lang.String addrDetail) {
		set("addr_detail", addrDetail);
		return (M)this;
	}
	
	public java.lang.String getAddrDetail() {
		return getStr("addr_detail");
	}

	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}
	
	public M setAddrType(java.lang.Long addrType) {
		set("addr_type", addrType);
		return (M)this;
	}
	
	public java.lang.Long getAddrType() {
		return getLong("addr_type");
	}

	public M setStatus(java.lang.Long status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Long getStatus() {
		return getLong("status");
	}
	
	public M setDeleted(java.lang.Long deleted) {
		set("deleted", deleted);
		return (M)this;
	}
	
	public java.lang.Long getDeleted() {
		return getLong("deleted");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
