package cn.joytur.modules.product.entities.base;

import com.jfinal.plugin.activerecord.IBean;

import cn.joytur.common.mvc.entities.DataModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGoods<M extends BaseGoods<M>> extends DataModel<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setGoodsName(java.lang.String goodsName) {
		set("goods_name", goodsName);
		return (M)this;
	}
	
	public java.lang.String getGoodsName() {
		return getStr("goods_name");
	}

	public M setGoodsImage(java.lang.String goodsImage) {
		set("goods_image", goodsImage);
		return (M)this;
	}
	
	public java.lang.String getGoodsImage() {
		return getStr("goods_image");
	}

	public M setRecommend(java.lang.String recommend) {
		set("recommend", recommend);
		return (M)this;
	}
	
	public java.lang.String getRecommend() {
		return getStr("recommend");
	}

	public M setMktPrice(java.lang.Double mktPrice) {
		set("mkt_price", mktPrice);
		return (M)this;
	}
	
	public java.lang.Double getMktPrice() {
		return getDouble("mkt_price");
	}
	
	public M setCostPrice(java.lang.Double costPrice) {
		set("cost_price", costPrice);
		return (M)this;
	}
	
	public java.lang.Double getCostPrice() {
		return getDouble("cost_price");
	}
	
	public M setScorePrice(java.lang.Long scorePrice) {
		set("score_price", scorePrice);
		return (M)this;
	}
	
	public java.lang.Long getScorePrice() {
		return getLong("score_price");
	}

	public M setCategoryId(java.lang.String categoryId) {
		set("category_id", categoryId);
		return (M)this;
	}
	
	public java.lang.String getCategoryId() {
		return getStr("category_id");
	}
	
	public M setGoodsRuleId(java.lang.String goodsRuleId) {
		set("goods_rule_id", goodsRuleId);
		return (M)this;
	}
	
	public java.lang.String getGoodsRuleId() {
		return getStr("goods_rule_id");
	}

	public M setMonthSales(java.lang.Long monthSales) {
		set("month_sales", monthSales);
		return (M)this;
	}
	
	public java.lang.Long getMonthSales() {
		return getLong("month_sales");
	}
	
	public M setStatus(java.lang.Long status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Long getStatus() {
		return getLong("status");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
