package cn.joytur.modules.product.entities.base;

import com.jfinal.plugin.activerecord.IBean;

import cn.joytur.common.mvc.entities.DataModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRechargeRule<M extends BaseRechargeRule<M>> extends DataModel<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setTransAmt(java.lang.Double transAmt) {
		set("trans_amt", transAmt);
		return (M)this;
	}
	
	public java.lang.Double getTransAmt() {
		return getDouble("trans_amt");
	}

	public M setTransAfterAmt(java.lang.Double transAfterAmt) {
		set("trans_after_amt", transAfterAmt);
		return (M)this;
	}
	
	public java.lang.Double getTransAfterAmt() {
		return getDouble("trans_after_amt");
	}

	public M setTransDayLimit(java.lang.Long transDayLimit) {
		set("trans_day_limit", transDayLimit);
		return (M)this;
	}
	
	public java.lang.Long getTransDayLimit() {
		return getLong("trans_day_limit");
	}

	public M setStatus(java.lang.Long status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Long getStatus() {
		return getLong("status");
	}

	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
