package cn.joytur.modules.product.entities.base;

import cn.joytur.common.mvc.entities.DataModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRechargeRuleQrCode<M extends BaseRechargeRuleQrCode<M>> extends DataModel<M> implements IBean {

	public M setId(String id) {
		set("id", id);
		return (M)this;
	}

	public String getId() {
		return getStr("id");
	}

	public M setRechargeRuleId(String rechargeRuleId) {
		set("recharge_rule_id", rechargeRuleId);
		return (M)this;
	}

	public String getRechargeRuleId() {
		return getStr("recharge_rule_id");
	}

	public M setTransAmt(Double transAmt) {
		set("trans_amt", transAmt);
		return (M)this;
	}

	public Double getTransAmt() {
		return getDouble("trans_amt");
	}

	public M setQrcodeType(Long qrcodeType) {
		set("qrcode_type", qrcodeType);
		return (M)this;
	}
	
	public Long getQrcodeType() {
		return getLong("qrcode_type");
	}
	
	public M setQrcodeImage(String qrcodeImage) {
		set("qrcode_image", qrcodeImage);
		return (M)this;
	}

	public String getQrcodeImage() {
		return getStr("qrcode_image");
	}
	
	public M setQrcodeUrl(String qrcodeUrl) {
		set("qrcode_url", qrcodeUrl);
		return (M)this;
	}

	public String getQrcodeUrl() {
		return getStr("qrcode_url");
	}

	public M setStatus(Long status) {
		set("status", status);
		return (M)this;
	}

	public Long getStatus() {
		return getLong("status");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
