package cn.joytur.modules.product.entities.base;

import com.jfinal.plugin.activerecord.IBean;

import cn.joytur.common.mvc.entities.DataModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGoodsGame<M extends BaseGoodsGame<M>> extends DataModel<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setGoodsId(java.lang.String goodsId) {
		set("goods_id", goodsId);
		return (M)this;
	}
	
	public java.lang.String getGoodsId() {
		return getStr("goods_id");
	}

	public M setWechatMemberId(java.lang.String wechatMemberId) {
		set("wechat_member_id", wechatMemberId);
		return (M)this;
	}
	
	public java.lang.String getWechatMemberId() {
		return getStr("wechat_member_id");
	}

	public M setExpAmt(java.lang.Double expAmt) {
		set("exp_amt", expAmt);
		return (M)this;
	}
	
	public java.lang.Double getExpAmt() {
		return getDouble("exp_amt");
	}

	public M setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
		return (M)this;
	}
	
	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public M setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
		return (M)this;
	}
	
	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public M setScreen(java.lang.String screen) {
		set("screen", screen);
		return (M)this;
	}
	
	public java.lang.String getScreen() {
		return getStr("screen");
	}

	public M setStatus(java.lang.Long status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Long getStatus() {
		return getLong("status");
	}
	
	public M setGameParams(java.lang.String gameParams) {
		set("game_params", gameParams);
		return (M)this;
	}
	
	public java.lang.String getGameParams() {
		return getStr("game_params");
	}
	
	public M setGameResult(java.lang.String gameResult) {
		set("game_result", gameResult);
		return (M)this;
	}
	
	public java.lang.String getGameResult() {
		return getStr("game_result");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
		return (M)this;
	}
	
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}

}
