package cn.joytur.modules.product.entities.base;

import com.jfinal.plugin.activerecord.IBean;

import cn.joytur.common.mvc.entities.DataModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseExtensionAdv<M extends BaseExtensionAdv<M>> extends DataModel<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public M setAdvType(java.lang.Long advType) {
		set("adv_type", advType);
		return (M)this;
	}
	
	public java.lang.Long getAdvType() {
		return getLong("adv_type");
	}
	
	public java.lang.String getAdvImage() {
		return getStr("adv_image");
	}

	public M setAdvImage(java.lang.String advImage) {
		set("adv_image", advImage);
		return (M)this;
	}
	
	public java.lang.String getAdvPara() {
		return getStr("adv_para");
	}

	public M setAdvPara(java.lang.String advPara) {
		set("adv_para", advPara);
		return (M)this;
	}
	
	public M setStatus(java.lang.Long status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Long getStatus() {
		return getLong("status");
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
