package cn.joytur.modules.wechat.entities;

import com.jfinal.plugin.activerecord.SqlPara;

import cn.joytur.common.annotation.TabMapping;
import cn.joytur.modules.wechat.entities.base.BaseWechatMemberProfit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TabMapping(tabName = "joy_wechat_member_profit")
public class WechatMemberProfit extends BaseWechatMemberProfit<WechatMemberProfit> {
	public static final WechatMemberProfit dao = new WechatMemberProfit().dao();
	
	/**
	 * 查询当前接收推荐用户的权益
	 * @param wechatMemberId
	 * @return
	 */
	public WechatMemberProfit findReceiveWechatMemberProfit(String wechatMemberId){
		SqlPara sqlPara = getSqlPara("wechatMemberProfit.findReceiveWechatMemberProfit", wechatMemberId);
		return findFirst(sqlPara);
	}
	
}
