package cn.joytur.modules.wechat.entities;

import java.util.List;

import com.jfinal.plugin.activerecord.SqlPara;

import cn.joytur.common.annotation.TabMapping;
import cn.joytur.modules.wechat.entities.base.BaseWechatTemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TabMapping(tabName = "joy_wechat_template")
public class WechatTemplate extends BaseWechatTemplate<WechatTemplate> {
	public static final WechatTemplate dao = new WechatTemplate().dao();
	
	/**
	 * 查询
	 * @param keywords
	 * @return
	 */
	public WechatTemplate findByKeywords(String keywords){
		SqlPara sqlPara = getSqlPara("wechatTemplate.findByKeywords", keywords);
		List<WechatTemplate> wechatTemplateList = find(sqlPara);
		
		if(wechatTemplateList == null || wechatTemplateList.isEmpty()){
			return null;
		}
		
		return wechatTemplateList.get(0);
	}
	
}
