package cn.joytur.modules.wechat.entities;

import java.util.List;

import cn.joytur.common.annotation.TabMapping;
import cn.joytur.modules.wechat.entities.base.BaseWechatSubscribe;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TabMapping(tabName = "joy_wechat_subscribe")
public class WechatSubscribe extends BaseWechatSubscribe<WechatSubscribe> {
	public static final WechatSubscribe dao = new WechatSubscribe().dao();
	
	/**
	 * 查询默认第一个
	 * @return
	 */
	public WechatSubscribe findDefault(){
		List<WechatSubscribe> allList = WechatSubscribe.dao.findAll();
		if(allList == null || allList.isEmpty()){
			return null;
		}
		return allList.get(0);
	}
	
}
