package cn.joytur.modules.product.entities;

import cn.joytur.common.annotation.TabMapping;
import cn.joytur.modules.product.entities.base.BaseExtensionRule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TabMapping(tabName = "joy_extension_rule")
public class ExtensionRule extends BaseExtensionRule<ExtensionRule> {
	public static final ExtensionRule dao = new ExtensionRule().dao();
}
