package cn.joytur.modules.product.entities;

import com.jfinal.kit.Kv;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.SqlPara;

import cn.joytur.common.annotation.TabMapping;
import cn.joytur.common.mvc.dto.Sort;
import cn.joytur.modules.product.entities.base.BaseGoodsGame;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TabMapping(tabName = "joy_goods_game")
public class GoodsGame extends BaseGoodsGame<GoodsGame> {
	public static final GoodsGame dao = new GoodsGame().dao();
	
	/**
	 * 分页查询
	 */
	public Page<GoodsGame> paginate(int pageNumber, int pageSize, GoodsGame query, Sort sort){
		SqlPara sqlPara = getSqlPara("goodsGame.findListPage", Kv.by("query", query));
		return paginate(pageNumber, pageSize, sqlPara);
	}
	
	/**
	 * 分页查询
	 */
	public Page<GoodsGame> paginateWap(int pageNumber, int pageSize, GoodsGame query, Sort sort){
		SqlPara sqlPara = getSqlPara("goodsGame.findListWapPage", Kv.by("query", query));
		return paginate(pageNumber, pageSize, sqlPara);
	}
	
}
