package cn.joytur.modules.product.entities;

import cn.joytur.common.annotation.TabMapping;
import cn.joytur.modules.product.entities.base.BaseGoodsRule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TabMapping(tabName = "joy_goods_rule")
public class GoodsRule extends BaseGoodsRule<GoodsRule> {
	public static final GoodsRule dao = new GoodsRule().dao();
}
