package cn.joytur.modules.product.entities;

import cn.joytur.common.annotation.TabMapping;
import cn.joytur.modules.product.entities.base.BaseGoodsCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TabMapping(tabName = "joy_goods_category")
public class GoodsCategory extends BaseGoodsCategory<GoodsCategory> {
	public static final GoodsCategory dao = new GoodsCategory().dao();
}
