package cn.joytur.modules.product.entities;

import java.util.List;

import com.jfinal.kit.Kv;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.SqlPara;

import cn.joytur.common.annotation.TabMapping;
import cn.joytur.common.mvc.dto.Sort;
import cn.joytur.modules.product.entities.base.BaseGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TabMapping(tabName = "joy_goods")
public class Goods extends BaseGoods<Goods> {
	public static final Goods dao = new Goods().dao();
	
	/**
	 * 分页查询
	 */
	public Page<Goods> paginate(int pageNumber, int pageSize, Goods query, Sort sort){
		SqlPara sqlPara = getSqlPara("goods.findListPage", Kv.by("query", query));
		return paginate(pageNumber, pageSize, sqlPara);
	}
	
	/**
	 * 充值满金额赠送
	 * @param wechatMemberId
	 * @return
	 */
	public List<Goods> findGiftGoodsList(String wechatMemberId) {
		SqlPara sqlPara = getSqlPara("goods.findGiftGoodsList", Kv.by("wechatMemberId", wechatMemberId));
		return find(sqlPara);
	}
	
}
