package cn.joytur.modules.product.entities;

import com.jfinal.kit.Kv;
import com.jfinal.plugin.activerecord.SqlPara;

import cn.joytur.common.annotation.TabMapping;
import cn.joytur.modules.product.entities.base.BaseRechargeRule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TabMapping(tabName = "joy_recharge_rule")
public class RechargeRule extends BaseRechargeRule<RechargeRule> {
	public static final RechargeRule dao = new RechargeRule().dao();
	
	public RechargeRule findByModel(RechargeRule query, Integer minAmt){
		Kv kv = Kv.by("query", query);
		if(minAmt != null){
			kv.set("minAmt", minAmt);
		}
		SqlPara sqlPara = getSqlPara("rechargeRule.findByModel", kv);
		return findFirst(sqlPara);
	}
}
