package cn.joytur.modules.system.entities;

import cn.joytur.common.annotation.TabMapping;
import cn.joytur.modules.system.entities.base.BaseSysConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TabMapping(tabName = "joy_sys_config")
public class SysConfig extends BaseSysConfig<SysConfig> {
	public static final SysConfig dao = new SysConfig().dao();
	
	/**
	 * 根据name查询配置
	 * @param name
	 * @return
	 */
	public SysConfig findByName(String name) {
		SysConfig quySysConfig = new SysConfig();
		quySysConfig.setName(name);
    	return findByModel(quySysConfig);
	}
	
}
