package cn.joytur.modules.system.entities;

import cn.joytur.common.annotation.TabMapping;
import cn.joytur.modules.system.entities.base.BaseSysDictionary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TabMapping(tabName = "joy_sys_dictionary")
public class SysDictionary extends BaseSysDictionary<SysDictionary> {
	public static final SysDictionary dao = new SysDictionary().dao();
	
	
}
