package cn.joytur.modules.system.entities;

import com.jfinal.plugin.activerecord.Db;

import cn.joytur.common.annotation.TabMapping;
import cn.joytur.modules.system.entities.base.BaseSysGfw;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TabMapping(tabName = "joy_sys_gfw")
public class SysGfw extends BaseSysGfw<SysGfw> {
	public static final SysGfw dao = new SysGfw().dao();
	
	/**
	 * 查询当前主要域名code
	 * @return
	 */
	public String findSelfAppCode(){
		return Db.queryStr(getSqlPara("sysGfw.findSelfAppCode").getSql()); 
	}
	
	/**
	 * 查询当前主要域名
	 * @return
	 */
	public String findSelfMasterUrl(){
		return Db.queryStr(getSqlPara("sysGfw.findSelfMasterUrl").getSql()); 
	}
	
	/**
	 * 查询当前从域名
	 * @return
	 */
	public String findSelfSlaveUrl(){
		return Db.queryStr(getSqlPara("sysGfw.findSelfSlaveUrl").getSql()); 
	}
	
	/**
	 * 查询第三方主要域名
	 * @return
	 */
	public String findOtherMasterUrl(String appCode){
		return Db.queryStr(getSqlPara("sysGfw.findOtherMasterUrl").getSql()); 
	}
	
	/**
	 * 查询第三方从域名
	 * @return
	 */
	public String findOtherSlaveUrl(String appCode){
		return Db.queryStr(getSqlPara("sysGfw.findOtherSlaveUrl").getSql(), appCode); 
	}
	
	/**
	 * 是否当前机器的self从域名
	 * @param appCode
	 * @return
	 */
	public boolean isSelfSlaveUrl(String appCode){
		SysGfw tmpSysGfw = findByModel(new SysGfw().setAppCode(appCode).setAppType(1l).setStatus(1L));
		if(tmpSysGfw == null){
			return false;
		}
		return true;
	}
}
