package cn.joytur.modules.system.entities;

import com.jfinal.plugin.activerecord.Db;

import cn.joytur.common.annotation.TabMapping;
import cn.joytur.modules.system.entities.base.BaseSysLoginLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TabMapping(tabName = "joy_sys_login_log")
public class SysLoginLog extends BaseSysLoginLog<SysLoginLog> {
	public static final SysLoginLog dao = new SysLoginLog().dao();
	
	/**
	 * 统计登录次数
	 * @param status
	 * @param userId
	 * @param datetime
	 * @return
	 */
	public int findCountByStatusAndUserIdAndMinute(Long status, String userId, String datetime) {
		return Db.queryInt(getSqlPara("loginLog.findCountByStatusAndUserIdAndMinute").getSql(), status, userId, datetime);
	}
	
	/**
	 * 删除所有日志
	 * @return
	 */
	public int deleteAll(){
		return Db.update(getSqlPara("loginLog.deleteAll").getSql());
	}
	
}
