package cn.joytur.modules.system.entities;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.SqlPara;

import cn.joytur.common.annotation.TabMapping;
import cn.joytur.modules.system.entities.base.BaseSysMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TabMapping(tabName = "joy_sys_menu")
public class SysMenu extends BaseSysMenu<SysMenu> {
	public static final SysMenu dao = new SysMenu().dao();
	
	/**
	 * 根据父级菜单ID获取本级全部菜单
	 * @param pid 父菜单ID
	 * @param notId 需要排除的菜单ID
	 * @return 
	 */
    public List<SysMenu> findByPidAndIdNot(String pid, String notId){
    	SqlPara sqlPara = getSqlPara("menu.findByPidAndIdNot", pid, notId);
    	return find(sqlPara);
    }
    
    /**
     * 查询排序最大的id
     * @return
     */
    public Long findMaxSort(String pid) {
    	SqlPara sqlPara = getSqlPara("menu.findByPidAndIdNot");
    	return Db.queryLong(sqlPara.getSql(), pid);
    }
    
    /**
     * 更新排序
     * @param id
     * @param sort
     * @return
     */
    public Integer updateSort(String id, Long sort){
    	SqlPara sqlPara = getSqlPara("menu.updateSort", sort, id);
    	return Db.update(sqlPara);
    }
    
}
