package cn.joytur.modules.system.entities;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

import cn.joytur.common.annotation.TabMapping;
import cn.joytur.modules.system.entities.base.BaseSysOperLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TabMapping(tabName = "joy_sys_oper_log")
public class SysOperLog extends BaseSysOperLog<SysOperLog> {
	public static final SysOperLog dao = new SysOperLog().dao();
	
	/**
	 * 异步线程保存
	 * @param sysOperLog
	 * @return
	 */
	public boolean threadSave(Record sysOperLog){
		 return Db.save(_getTable().getName(), sysOperLog);
	}
	
	/**
	 * 删除所有日志
	 * @return
	 */
	public int deleteAll(){
		return Db.update(getSqlPara("operLog.deleteAll").getSql());
	}
	
}
