package cn.joytur.modules.system.entities;

import cn.joytur.common.annotation.TabMapping;
import cn.joytur.modules.system.entities.SysRole;
import cn.joytur.modules.system.entities.base.BaseSysRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TabMapping(tabName = "joy_sys_role")
public class SysRole extends BaseSysRole<SysRole> {
	public static final SysRole dao = new SysRole().dao();
}
