package cn.joytur.modules.system.entities;

import cn.joytur.common.annotation.TabMapping;
import cn.joytur.modules.system.entities.SysUserRole;
import cn.joytur.modules.system.entities.base.BaseSysUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TabMapping(tabName = "joy_sys_user_role")
public class SysUserRole extends BaseSysUserRole<SysUserRole> {
	public static final SysUserRole dao = new SysUserRole().dao();
}
