package cn.joytur.modules.order.entites.base;

import com.jfinal.plugin.activerecord.IBean;

import cn.joytur.common.mvc.entities.DataModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGoodsOrder<M extends BaseGoodsOrder<M>> extends DataModel<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
		return (M)this;
	}
	
	public java.lang.String getOrderNo() {
		return getStr("order_no");
	}

	public M setWechatMemberId(java.lang.String wechatMemberId) {
		set("wechat_member_id", wechatMemberId);
		return (M)this;
	}
	
	public java.lang.String getWechatMemberId() {
		return getStr("wechat_member_id");
	}

	public M setGameId(java.lang.String gameId) {
		set("game_id", gameId);
		return (M)this;
	}
	
	public java.lang.String getGameId() {
		return getStr("game_id");
	}

	public M setGoodsId(java.lang.String goodsId) {
		set("goods_id", goodsId);
		return (M)this;
	}
	
	public java.lang.String getGoodsId() {
		return getStr("goods_id");
	}

	public M setStatus(java.lang.Long status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Long getStatus() {
		return getLong("status");
	}
	
	public M setOrderType(java.lang.Long orderType) {
		set("order_type", orderType);
		return (M)this;
	}
	
	public java.lang.Long getOrderType() {
		return getLong("order_type");
	}

	public M setAddrMirror(java.lang.String addrMirror) {
		set("addr_mirror", addrMirror);
		return (M)this;
	}
	
	public java.lang.String getAddrMirror() {
		return getStr("addr_mirror");
	}

	public M setLogisticsNumber(java.lang.String logisticsNumber) {
		set("logistics_number", logisticsNumber);
		return (M)this;
	}
	
	public java.lang.String getLogisticsNumber() {
		return getStr("logistics_number");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
