package cn.joytur.modules.order.entites.base;

import com.jfinal.plugin.activerecord.IBean;

import cn.joytur.common.mvc.entities.DataModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRechargeOrder<M extends BaseRechargeOrder<M>> extends DataModel<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setWechatMemberId(java.lang.String wechatMemberId) {
		set("wechat_member_id", wechatMemberId);
		return (M)this;
	}

	public java.lang.String getWechatMemberId() {
		return getStr("wechat_member_id");
	}

	public M setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
		return (M)this;
	}
	
	public java.lang.String getOrderNo() {
		return getStr("order_no");
	}
	
	public M setTransType(java.lang.Long transType) {
		set("trans_type", transType);
		return (M)this;
	}
	
	public java.lang.Long getTransType() {
		return getLong("trans_type");
	}

	public M setTransAmt(java.lang.Double transAmt) {
		set("trans_amt", transAmt);
		return (M)this;
	}
	
	public java.lang.Double getTransAmt() {
		return getDouble("trans_amt");
	}
	
	public M setRealTransAmt(java.lang.Double realTransAmt) {
		set("real_trans_amt", realTransAmt);
		return (M)this;
	}
	
	public java.lang.Double getRealTransAmt() {
		return getDouble("real_trans_amt");
	}

	public M setTransAfterAmt(java.lang.Double transAfterAmt) {
		set("trans_after_amt", transAfterAmt);
		return (M)this;
	}
	
	public java.lang.Double getTransAfterAmt() {
		return getDouble("trans_after_amt");
	}

	public M setStatus(java.lang.Long status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Long getStatus() {
		return getLong("status");
	}
	
	public M setCommissionStatus(java.lang.Long commissionStatus) {
		set("commission_status", commissionStatus);
		return (M)this;
	}
	
	public java.lang.Long getCommissionStatus() {
		return getLong("commission_status");
	}

	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}
	
	public M setRechargeRuleId(java.lang.String rechargeRuleId) {
		set("recharge_rule_id", rechargeRuleId);
		return (M)this;
	}
	
	public java.lang.String getRechargeRuleId() {
		return getStr("recharge_rule_id");
	}
	
	public M setQrcodeType(java.lang.Long qrcodeType) {
		set("qrcode_type", qrcodeType);
		return (M)this;
	}
	
	public java.lang.Long getQrcodeType() {
		return getLong("qrcode_type");
	}
	
	public M setQrcodeImage(java.lang.String qrcodeImage) {
		set("qrcode_image", qrcodeImage);
		return (M)this;
	}
	
	public java.lang.String getQrcodeImage() {
		return getStr("qrcode_image");
	}
	
	public M setActionType(java.lang.Long action_type) {
		set("action_type", action_type);
		return (M)this;
	}
	
	public java.lang.Long getMailStatus() {
		return getLong("mail_status");
	}
	
	public M setMailStatus(java.lang.Long mailStatus) {
		set("mail_status", mailStatus);
		return (M)this;
	}
	
	public java.lang.Long getActionType() {
		return getLong("action_type");
	}

	public M setExpireTime(java.util.Date expireTime) {
		set("expire_time", expireTime);
		return (M)this;
	}

	public java.util.Date getExpireTime() {
		return get("expire_time");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
