package cn.joytur.modules.order.entites.base;

import com.jfinal.plugin.activerecord.IBean;

import cn.joytur.common.mvc.entities.DataModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAccountFunds<M extends BaseAccountFunds<M>> extends DataModel<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setWechatMemberId(java.lang.String wechatMemberId) {
		set("wechat_member_id", wechatMemberId);
		return (M)this;
	}
	
	public java.lang.String getWechatMemberId() {
		return getStr("wechat_member_id");
	}
	
	public M setFromAccountId(java.lang.String fromAccountId) {
		set("from_account_id", fromAccountId);
		return (M)this;
	}
	
	public java.lang.String getFromAccountId() {
		return getStr("from_account_id");
	}

	public M setAccType(java.lang.Long accType) {
		set("acc_type", accType);
		return (M)this;
	}
	
	public java.lang.Long getAccType() {
		return getLong("acc_type");
	}

	public M setToAccountId(java.lang.String toAccountId) {
		set("to_account_id", toAccountId);
		return (M)this;
	}
	
	public java.lang.String getToAccountId() {
		return getStr("to_account_id");
	}

	public M setTransAmt(java.lang.Double transAmt) {
		set("trans_amt", transAmt);
		return (M)this;
	}
	
	public java.lang.Double getTransAmt() {
		return getDouble("trans_amt");
	}

	public M setTransType(java.lang.Long transType) {
		set("trans_type", transType);
		return (M)this;
	}
	
	public java.lang.Long getTransType() {
		return getLong("trans_type");
	}

	public M setEleType(java.lang.Long eleType) {
		set("ele_type", eleType);
		return (M)this;
	}
	
	public java.lang.Long getEleType() {
		return getLong("ele_type");
	}

	public M setBefAmt(java.lang.Double befAmt) {
		set("bef_amt", befAmt);
		return (M)this;
	}
	
	public java.lang.Double getBefAmt() {
		return getDouble("bef_amt");
	}

	public M setAftAmt(java.lang.Double aftAmt) {
		set("aft_amt", aftAmt);
		return (M)this;
	}
	
	public java.lang.Double getAftAmt() {
		return getDouble("aft_amt");
	}
	
	public M setTag(java.lang.String tag) {
		set("tag", tag);
		return (M)this;
	}
	
	public java.lang.String getTag() {
		return getStr("tag");
	}

	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
