package cn.joytur.modules.order.entites.base;

import com.jfinal.plugin.activerecord.IBean;

import cn.joytur.common.mvc.entities.DataModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAccount<M extends BaseAccount<M>> extends DataModel<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setWechatMemberId(java.lang.String wechatMemberId) {
		set("wechat_member_id", wechatMemberId);
		return (M)this;
	}
	
	public java.lang.String getWechatMemberId() {
		return getStr("wechat_member_id");
	}

	public M setTotalAmt(java.lang.Double totalAmt) {
		set("total_amt", totalAmt);
		return (M)this;
	}
	
	public java.lang.Double getTotalAmt() {
		return getDouble("total_amt");
	}

	public M setFrzAmt(java.lang.Double frzAmt) {
		set("frz_amt", frzAmt);
		return (M)this;
	}
	
	public java.lang.Double getFrzAmt() {
		return getDouble("frz_amt");
	}

	public M setAvbAmt(java.lang.Double avbAmt) {
		set("avb_amt", avbAmt);
		return (M)this;
	}
	
	public java.lang.Double getAvbAmt() {
		return getDouble("avb_amt");
	}

	public M setAccType(java.lang.Long accType) {
		set("acc_type", accType);
		return (M)this;
	}
	
	public java.lang.Long getAccType() {
		return getLong("acc_type");
	}

	public M setStatus(java.lang.Long status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Long getStatus() {
		return getLong("status");
	}

	public M setVersion(java.lang.Long version) {
		set("version", version);
		return (M)this;
	}
	
	public java.lang.Long getVersion() {
		return getLong("version");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
