package cn.joytur.modules.system.entities.base;

import com.jfinal.plugin.activerecord.IBean;

import cn.joytur.common.mvc.entities.DataModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysOperLog<M extends BaseSysOperLog<M>> extends DataModel<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setType(java.lang.Long type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Long getType() {
		return getLong("type");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setRemoteAddr(java.lang.String remoteAddr) {
		set("remote_addr", remoteAddr);
		return (M)this;
	}
	
	public java.lang.String getRemoteAddr() {
		return getStr("remote_addr");
	}

	public M setUserAgent(java.lang.String userAgent) {
		set("user_agent", userAgent);
		return (M)this;
	}
	
	public java.lang.String getUserAgent() {
		return getStr("user_agent");
	}

	public M setRequestUri(java.lang.String requestUri) {
		set("request_uri", requestUri);
		return (M)this;
	}
	
	public java.lang.String getRequestUri() {
		return getStr("request_uri");
	}

	public M setRequestMethod(java.lang.String requestMethod) {
		set("request_method", requestMethod);
		return (M)this;
	}
	
	public java.lang.String getRequestMethod() {
		return getStr("request_method");
	}

	public M setParams(java.lang.String params) {
		set("params", params);
		return (M)this;
	}
	
	public java.lang.String getParams() {
		return getStr("params");
	}

	public M setException(java.lang.String exception) {
		set("exception", exception);
		return (M)this;
	}
	
	public java.lang.String getException() {
		return getStr("exception");
	}
	
	public M setResponse(java.lang.String response) {
		set("response", response);
		return (M)this;
	}
	
	public java.lang.String getResponse() {
		return getStr("response");
	}
	
	public M setConsumeMs(java.lang.String consumeMs) {
		set("consume_ms", consumeMs);
		return (M)this;
	}
	
	public java.lang.String getConsumeMs() {
		return getStr("consume_ms");
	}

	public M setCreateUserId(java.lang.String createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}
	
	public java.lang.String getCreateUserId() {
		return getStr("create_user_id");
	}

	public M setCreateUserName(java.lang.String createUserName) {
		set("create_user_name", createUserName);
		return (M)this;
	}
	
	public java.lang.String getCreateUserName() {
		return getStr("create_user_name");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
