package cn.joytur.modules.system.entities.base;

import com.jfinal.plugin.activerecord.IBean;

import cn.joytur.common.mvc.entities.DataModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysGfw<M extends BaseSysGfw<M>> extends DataModel<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setAppName(java.lang.String appName) {
		set("app_name", appName);
		return (M)this;
	}
	
	public java.lang.String getAppName() {
		return getStr("app_name");
	}
	
	public M setAppCode(java.lang.String appCode) {
		set("app_code", appCode);
		return (M)this;
	}
	
	public java.lang.String getAppCode() {
		return getStr("app_code");
	}
	
	public M setAppType(java.lang.Long appType) {
		set("app_type", appType);
		return (M)this;
	}
	
	public java.lang.Long getAppType() {
		return getLong("app_type");
	}
	
	public M setVarUrl(java.lang.String varUrl) {
		set("var_url", varUrl);
		return (M)this;
	}
	
	public java.lang.String getVarUrl() {
		return getStr("var_url");
	}
	
	public M setMasterUrl(java.lang.String masterUrl) {
		set("master_url", masterUrl);
		return (M)this;
	}
	
	public java.lang.String getMasterUrl() {
		return getStr("master_url");
	}
	
	public M setSlaveUrl(java.lang.String slaveUrl) {
		set("slave_url", slaveUrl);
		return (M)this;
	}
	
	public java.lang.String getSlaveUrl() {
		return getStr("slave_url");
	}

	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}
	
	public M setStatus(java.lang.Long status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Long getStatus() {
		return getLong("status");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	public M setUpdateTime(java.util.Date createTime) {
		set("update_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
