package cn.joytur.modules.order.entites;

import com.jfinal.kit.Kv;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.SqlPara;

import cn.joytur.common.annotation.TabMapping;
import cn.joytur.common.mvc.constant.DictAttribute;
import cn.joytur.common.mvc.dto.Sort;
import cn.joytur.common.utils.JoyDictUtil;
import cn.joytur.modules.order.entites.base.BaseAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TabMapping(tabName = "joy_account")
public class Account extends BaseAccount<Account> {
	public static final Account dao = new Account().dao();
	
	/**
	 * 分页查询
	 */
	public Page<Account> paginate(int pageNumber, int pageSize, Account query, Sort sort){
		SqlPara sqlPara = getSqlPara("account.findListPage", Kv.by("query", query));
		return paginate(pageNumber, pageSize, sqlPara);
	}
	
	/**
	 * 获取游戏账户
	 * @return
	 */
	public Account getGameAccount(String wechatMemberId) {
		String accType = JoyDictUtil.getDictValue(DictAttribute.ACCOUNT_ACC_TYPE_GAME, DictAttribute.ACCOUNT_ACC_TYPE, "3");
		Account tmpAccount = Account.dao.findByModel(new Account().setWechatMemberId(wechatMemberId).setAccType(Long.valueOf(accType)).setStatus(1L));
		return tmpAccount;
	}
	
	/**
	 * 获取结算账户
	 * @return
	 */
	public Account getSettAccount(String wechatMemberId) {
		String accType = JoyDictUtil.getDictValue(DictAttribute.ACCOUNT_ACC_TYPE_SETT, DictAttribute.ACCOUNT_ACC_TYPE, "4");
		Account tmpAccount = Account.dao.findByModel(new Account().setWechatMemberId(wechatMemberId).setAccType(Long.valueOf(accType)).setStatus(1L));
		return tmpAccount;
	}
	
	/**
	 * 获取内部游戏账户
	 * @return
	 */
	public Account getInsideGameAccount() {
		String accType = JoyDictUtil.getDictValue(DictAttribute.ACCOUNT_ACC_TYPE_INSIDE_GAME, DictAttribute.ACCOUNT_ACC_TYPE, "1");
		Account tmpAccount = Account.dao.findByModel(new Account().setAccType(Long.valueOf(accType)));
		return tmpAccount;
	}
	
	/**
	 * 获取内部结算账户
	 * @return
	 */
	public Account getInsideSettAccount() {
		String accType = JoyDictUtil.getDictValue(DictAttribute.ACCOUNT_ACC_TYPE_INSIDE_SETT, DictAttribute.ACCOUNT_ACC_TYPE, "2");
		Account tmpAccount = Account.dao.findByModel(new Account().setAccType(Long.valueOf(accType)));
		return tmpAccount;
	}
	
}
