package cn.joytur.modules.order.entites;

import com.jfinal.kit.Kv;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.SqlPara;

import cn.joytur.common.annotation.TabMapping;
import cn.joytur.common.mvc.dto.Sort;
import cn.joytur.modules.order.entites.base.BaseAccountFunds;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TabMapping(tabName = "joy_account_funds")
public class AccountFunds extends BaseAccountFunds<AccountFunds> {
	public static final AccountFunds dao = new AccountFunds().dao();
	
	/**
	 * 分页查询
	 */
	public Page<AccountFunds> paginate(int pageNumber, int pageSize, AccountFunds query, Sort sort){
		SqlPara sqlPara = getSqlPara("accountFunds.findListPage", Kv.by("query", query));
		return paginate(pageNumber, pageSize, sqlPara);
	}
	
}
