package cn.joytur.modules.order.entites;

import java.util.List;

import com.jfinal.kit.Kv;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.SqlPara;

import cn.joytur.common.annotation.TabMapping;
import cn.joytur.common.mvc.constant.DictAttribute;
import cn.joytur.common.mvc.dto.Sort;
import cn.joytur.common.utils.JoyDictUtil;
import cn.joytur.modules.order.entites.base.BaseGoodsOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TabMapping(tabName = "joy_goods_order")
public class GoodsOrder extends BaseGoodsOrder<GoodsOrder> {
	public static final GoodsOrder dao = new GoodsOrder().dao();
	
	/**
	 * 分页查询
	 */
	public Page<GoodsOrder> paginate(int pageNumber, int pageSize, GoodsOrder query, Sort sort){
		SqlPara sqlPara = getSqlPara("goodsOrder.findListPage", Kv.by("query", query));
		return paginate(pageNumber, pageSize, sqlPara);
	}
	
	/**
	 * 分页查询
	 */
	public Page<GoodsOrder> wapPaginate(int pageNumber, int pageSize, GoodsOrder query, Sort sort){
		SqlPara sqlPara = getSqlPara("goodsOrder.findWapListPage", Kv.by("query", query));
		return paginate(pageNumber, pageSize, sqlPara);
	}
	
	/**
	 * 获取通知展示
	 * @param size
	 * @return
	 */
	public List<GoodsOrder> findNoticeList(int size){
		SqlPara sqlPara = getSqlPara("goodsOrder.findNoticeList", size);
		return find(sqlPara);
	}
	
	/**
	 * 查询待提现订单
	 * @return
	 */
	public Integer findCountByWait(){
		SqlPara sqlPara = getSqlPara("goodsOrder.findCountByWait");
		String status = JoyDictUtil.getDictValue(DictAttribute.GOODS_ORDER_STATUS1, DictAttribute.GOODS_ORDER_STATUS, "3");
		return Db.queryInt(sqlPara.getSql(), status);
	}
}
