package cn.joytur.modules.order.entites;

import com.jfinal.kit.Kv;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.SqlPara;

import cn.joytur.common.annotation.TabMapping;
import cn.joytur.common.mvc.constant.DictAttribute;
import cn.joytur.common.mvc.dto.Sort;
import cn.joytur.common.utils.JoyDictUtil;
import cn.joytur.modules.order.entites.base.BaseRecommendOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TabMapping(tabName = "joy_recommend_order")
public class RecommendOrder extends BaseRecommendOrder<RecommendOrder> {
	public static final RecommendOrder dao = new RecommendOrder().dao();
	
	/**
	 * 分页查询
	 */
	public Page<RecommendOrder> paginate(int pageNumber, int pageSize, RecommendOrder query, Sort sort){
		SqlPara sqlPara = getSqlPara("recommendOrder.findListPage", Kv.by("query", query));
		return paginate(pageNumber, pageSize, sqlPara);
	}
	
	/**
	 * 查询待提现订单
	 * @return
	 */
	public Integer findCountByWait(){
		SqlPara sqlPara = getSqlPara("recommendOrder.findCountByWait");
		String status = JoyDictUtil.getDictValue(DictAttribute.RECOMMEND_ORDER_STATUS_APPLY, DictAttribute.RECOMMEND_ORDER_STATUS, "3");
		return Db.queryInt(sqlPara.getSql(), status);
	}
}
